.PHONY: test
test:
	@echo "Running tests..."
	go test -v ./...

.PHONY: format
format:
	@echo "Formatting code..."
	go fmt ./...

.PHONY: generate
generate:
	@echo "Generating code..."
	go generate ./...
